### ISSUE TITLE
[jss-vender-prefixer]  Unable to build

### ISSUE THREAD

**Issue by gcallaghan** [jsstyles/jss#185]
```
$ npm i

> jss-vendor-prefixer@1.0.0 prepublish /Users/grant/src/jss-vendor-prefixer
> npm run all && git push --tags


> jss-vendor-prefixer@1.0.0 all /Users/grant/src/jss-vendor-prefixer
> npm run lint && npm run build


> jss-vendor-prefixer@1.0.0 lint /Users/grant/src/jss-vendor-prefixer
> eslint ./src

TypeError: Cannot read property 'visitClass' of undefined
    at monkeypatch (/Users/grant/src/jss-vendor-prefixer/node_modules/babel-eslint/index.js:199:40)
    at Object.exports.parse (/Users/grant/src/jss-vendor-prefixer/node_modules/babel-eslint/index.js:410:5)
    at parse (/Users/grant/src/jss-vendor-prefixer/node_modules/eslint/lib/eslint.js:449:27)
    at EventEmitter.module.exports.api.verify (/Users/grant/src/jss-vendor-prefixer/node_modules/eslint/lib/eslint.js:603:15)
    at processText (/Users/grant/src/jss-vendor-prefixer/node_modules/eslint/lib/cli-engine.js:201:27)
    at processFile (/Users/grant/src/jss-vendor-prefixer/node_modules/eslint/lib/cli-engine.js:226:12)
    at /Users/grant/src/jss-vendor-prefixer/node_modules/eslint/lib/cli-engine.js:322:26
    at /Users/grant/src/jss-vendor-prefixer/node_modules/eslint/lib/util/traverse.js:61:17
    at Array.forEach (native)
    at traverse (/Users/grant/src/jss-vendor-prefixer/node_modules/eslint/lib/util/traverse.js:41:54)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.4.1_1/bin/node" "/usr/local/bin/npm" "run" "lint"
npm ERR! node v5.4.1
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! jss-vendor-prefixer@1.0.0 lint: `eslint ./src`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jss-vendor-prefixer@1.0.0 lint script 'eslint ./src'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jss-vendor-prefixer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint ./src
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jss-vendor-prefixer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jss-vendor-prefixer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/grant/src/jss-vendor-prefixer/npm-debug.log

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.4.1_1/bin/node" "/usr/local/bin/npm" "run" "all"
npm ERR! node v5.4.1
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! jss-vendor-prefixer@1.0.0 all: `npm run lint && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jss-vendor-prefixer@1.0.0 all script 'npm run lint && npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jss-vendor-prefixer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run lint && npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jss-vendor-prefixer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jss-vendor-prefixer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/grant/src/jss-vendor-prefixer/npm-debug.log

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.4.1_1/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v5.4.1
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! jss-vendor-prefixer@1.0.0 prepublish: `npm run all && git push --tags`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jss-vendor-prefixer@1.0.0 prepublish script 'npm run all && git push --tags'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jss-vendor-prefixer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run all && git push --tags
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jss-vendor-prefixer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jss-vendor-prefixer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/grant/src/jss-vendor-p
```

```
$ node -v
v5.4.1
$ npm -v
3.5.3
```

**Comment by kof** [comment]
I think its related to that specific node/npm/babel bundle, so yeah, we should update dependencies.
