### ISSUE TITLE
[css-vendor] does not work when server-side rendering

### ISSUE THREAD

**Issue by b2whats** [jsstyles/jss#205]
https://github.com/jsstyles/css-vendor/blob/master/src/supported-property.js#L40

What will happen if i run 'jss.use(vendorPrefixer());' in server ? 

```
 error given was: TypeError: Cannot read property 'style' of undefined
[1]     at Object.supportedProperty (/home/parallels/WebstormProjects/paulcamper-webapp/node_modules/css-vendor/lib/supported-property.js:54:42)
[1]     at Array.<anonymous> (/home/parallels/WebstormProjects/paulcamper-webapp/node_modules/react-images/node_modules/jss-vendor-prefixer/lib/index.js:32:34)
[1]     at PluginsRegistry.run (/home/parallels/WebstormProjects/paulcamper-webapp/node_modules/jss/lib/PluginsRegistry.js:49:29)
[1]     at StyleSheet.createRule (/home/parallels/WebstormProjects/paulcamper-webapp/node_modules/jss/lib/StyleSheet.js:213:27)
[1]     at new StyleSheet (/home/parallels/WebstormProjects/paulcamper-webapp/node_modules/jss/lib/StyleSheet.js:60:12)
[1]     at Jss.createStyleSheet (/home/parallels/WebstormProjects/paulcamper-webapp/node_modules/jss/lib/Jss.js:78:19)
[1]     at attach (/home/parallels/WebstormProjects/paulcamper-webapp/node_modules/react-jss/lib/index.js:38:30)
[1]     at ref (/home/parallels/WebstormProjects/paulcamper-webapp/node_modules/react-jss/lib/index.js:47:21)
[1]     at StyleSheetWrapper.componentWillMount (/home/parallels/WebstormProjects/paulcamper-webapp/node_modules/react-jss/lib/index.js:71:22)
[1]     at [object Object].ReactCompositeComponentMixin.mountComponent (/home/parallels/WebstormProjects/paulcamper-webapp/node_modules/react/lib/ReactCompositeComponent.js:210:12)

```

**Comment by kof** [comment]
oh thats a bug, nothing should happen at all

**Comment by kof** [comment]
published a new version, try it out, let me know if it doesn't work.
